### ISSUE TITLE
variable port_info seems to be required

### ISSUE THREAD

**Issue by findmyname666** [clouddrove/terraform-aws-lightsail#11]
Terraform run fails when variables `port_info` isn't provided.

```
module.lightsail.module.lightsail.data.aws_region.default: Reading...
module.lightsail.module.lightsail.data.aws_region.default: Read complete after 0s [id=eu-central-1]
2023-01-01T16:43:52.681+0100 [ERROR] vertex "module.lightsail.module.lightsail.aws_lightsail_instance_public_ports.public" error: Insufficient port_info blocks
2023-01-01T16:43:52.681+0100 [ERROR] vertex "module.lightsail.module.lightsail.aws_lightsail_instance_public_ports.public" error: Insufficient port_info blocks
2023-01-01T16:43:52.681+0100 [ERROR] vertex "module.lightsail.module.lightsail.aws_lightsail_instance_public_ports.public (expand)" error: Insufficient port_info blocks
╷
│ Error: Insufficient port_info blocks
│ 
│   on .terraform/modules/lightsail.lightsail/main.tf line 45, in resource "aws_lightsail_instance_public_ports" "public":
│   45: resource "aws_lightsail_instance_public_ports" "public" {
│ 
│ At least 1 "port_info" blocks are required.
```

Port info is required on a resource **aws_lightsail_instance_public_ports** - [doc](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_instance_public_ports).

**Comment by theprashantyadav** [comment]
@findmyname666 
Hii
there are already used `port_info`  you can check
https://github.com/clouddrove/terraform-aws-lightsail/blob/master/main.tf#L48-L61

**Comment by findmyname666** [comment]
> @findmyname666 Hii there are already used `port_info` you can check https://github.com/clouddrove/terraform-aws-lightsail/blob/master/main.tf#L48-L61

Hi @theprashantyadav,

This issue isn't about feature to use `port_info` but it is about runtime bug that module execution fails when port_info isn't defined as stated in the description. Could you pls reopen this issue ? Thx.
