### ISSUE TITLE
No way to access ssh host key as output for aws_lightsail_instance?

### ISSUE THREAD

**Issue by e12e** [clouddrove/terraform-aws-lightsail#22]
While it is possible to specify a ssh user public key for access - there appear to be no way to access the generated public sshd server side key - and so no way to securely connect to the created instance (one must simply trust-on-first-use).

I believe the data should be available in the api?

 * https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/API_InstanceAccessDetails.html
 * https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/API_HostKeyAttributes.html

**Comment by d4kverma** [comment]
> While it is possible to specify a ssh user public key for access - there appear to be no way to access the generated public sshd server side key - and so no way to securely connect to the created instance (one must simply trust-on-first-use).
> 
> I believe the data should be available in the api?
> 
> * https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/API_InstanceAccessDetails.html
> * https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/API_HostKeyAttributes.html

Okay let us check this.

**Comment by d4kverma** [comment]
closing issue now .. Created new tag .

**Comment by e12e** [comment]
> closing issue now .. Created new tag .

What does this refer to? Is there supposed to be new output for hostkey?

https://github.com/clouddrove/terraform-aws-lightsail/tree/1.3.1#outputs
